import { StyleSheet } from "react-native";
import { ThemeColors } from "../../context/ThemeContext";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },
    loadingText: {
      fontSize: 16,
      color: colors.textSecondary,
      marginTop: 16,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
      padding: 32,
    },
    emptyIconWrapper: {
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: colors.primaryLight,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 20,
    },
    emptyTitle: {
      fontSize: 22,
      color: colors.textPrimary,
      fontWeight: "700",
      marginBottom: 8,
      textAlign: "center",
    },
    emptySubtext: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: "center",
      lineHeight: 22,
      maxWidth: 280,
    },
    // Summary cards – 2x2 grid
    summaryRow: {
      flexDirection: "row",
      paddingHorizontal: 16,
      gap: 10,
    },
    summaryCard: {
      flex: 1,
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    summaryIconWrapper: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 8,
    },
    summaryValue: {
      fontSize: 20,
      color: colors.textPrimary,
      fontWeight: "700",
    },
    summaryLabel: {
      fontSize: 11,
      color: colors.textTertiary,
      marginTop: 2,
      textAlign: "center",
      fontWeight: "500",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    // Section headers
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 4,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textTertiary,
      textTransform: "uppercase",
      letterSpacing: 1,
      marginLeft: 8,
    },
    // Friend ranking
    rankingContainer: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      marginHorizontal: 16,
      marginTop: 4,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    rankingTitle: {
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 12,
      fontWeight: "700",
    },
    rankingItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.borderLight,
    },
    rankingItemLast: {
      borderBottomWidth: 0,
    },
    rankingLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    rankingBadge: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    rankingPosition: {
      fontSize: 10,
      color: colors.textInverse,
      fontWeight: "bold",
    },
    friendAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.primaryLight,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    friendAvatarText: {
      fontSize: 15,
      color: colors.primary,
      fontWeight: "600",
    },
    friendName: {
      fontSize: 15,
      color: colors.textPrimary,
      flex: 1,
      fontWeight: "500",
    },
    friendAmount: {
      fontSize: 15,
      color: colors.primary,
      fontWeight: "700",
    },
    // Most expensive expense
    expenseContainer: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      marginHorizontal: 16,
      marginTop: 4,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    expenseTitle: {
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 12,
      fontWeight: "700",
    },
    expenseCard: {
      backgroundColor: colors.backgroundDark,
      borderRadius: 12,
      padding: 14,
    },
    expenseHeader: {
      flexDirection: "row",
      alignItems: "center",
    },
    expenseIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.primaryLight,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    expenseDetails: {
      flex: 1,
    },
    expenseDescription: {
      fontSize: 15,
      color: colors.textPrimary,
      fontWeight: "600",
      marginBottom: 3,
    },
    expenseCategory: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: "500",
      marginBottom: 2,
    },
    expenseDate: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    expenseAmount: {
      fontSize: 18,
      color: colors.textPrimary,
      fontWeight: "800",
    },
    bottomSpacer: {
      height: 32,
    },
  });
