import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  heroCard: {
    backgroundColor: "#5bc5a7",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
  },
  categoryIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.25)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  heroAmount: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  heroDescription: {
    fontSize: 18,
    color: "rgba(255,255,255,0.9)",
    marginBottom: 4,
  },
  heroDate: {
    fontSize: 13,
    color: "rgba(255,255,255,0.75)",
  },
  section: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 13,
    color: "#888",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  detailLabel: {
    fontSize: 14,
    color: "#888",
  },
  detailValue: {
    fontSize: 14,
    color: "#333",
    fontWeight: "500",
    maxWidth: "60%",
    textAlign: "right",
  },
  splitRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  splitAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f0faf9",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  splitAvatarText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#5bc5a7",
  },
  splitName: {
    flex: 1,
    fontSize: 15,
    color: "#333",
  },
  splitAmount: {
    fontSize: 15,
    fontWeight: "600",
    color: "#333",
  },
  // Edit mode
  editField: {
    borderWidth: 1.5,
    borderColor: "#5bc5a7",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 15,
    color: "#333",
    marginBottom: 8,
  },
  editLabel: {
    fontSize: 13,
    color: "#888",
    marginBottom: 4,
  },
  categoryPicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#e0e0e0",
    backgroundColor: "#fafafa",
  },
  categoryChipSelected: {
    borderColor: "#5bc5a7",
    backgroundColor: "#f0faf9",
  },
  categoryChipText: {
    fontSize: 13,
    color: "#555",
  },
  categoryChipTextSelected: {
    color: "#5bc5a7",
    fontWeight: "700",
  },
  // Action buttons
  actionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  editButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#5bc5a7",
  },
  editButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  deleteButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#F44336",
  },
  deleteButtonText: {
    color: "#F44336",
    fontSize: 16,
    fontWeight: "bold",
  },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#5bc5a7",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  cancelEditButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#bbb",
  },
  cancelEditButtonText: {
    color: "#888",
    fontSize: 16,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  tag: {
    backgroundColor: "#f0faf9",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  tagText: {
    color: "#5bc5a7",
    fontSize: 12,
    fontWeight: "600",
  },
});
